name: Configured
on:
  push:
  workflow_dispatch:
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_wrapper: false
      - run: terraform init
        working-directory: github
      - run: terraform plan -detailed-exitcode
        working-directory: github
        env:
          TF_VAR_GITHUB_TOKEN: ${{ secrets.GH_PAT_FOR_TERRAFORM_PLAN }}
